### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bdring** [danielvarga/string-art#1]
Is it possible to fix the broken links in the readme.md?

**Comment by kalkoen** [comment]
A gentle bump! Would love to see the results images! Is @danielvarga still active?

**Comment by kalkoen** [comment]
For anyone still wondering, You can see the images on the WayBack machine: https://web.archive.org/web/20201111180617/https://github.com/danielvarga/string-art

**Comment by danielvarga** [comment]
Thank you @kalkoen! I didn't have the originals anymore, and I never got around to recreating them, but your Wayback link was enough of a nudge for me to fix this! I'm sorry it took so long!
