### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by arrrrrrrri** [danielvarga/string-art#2]
I am quite confused with those code.What does it used for?
pixel_code = (pixel[1]+radius)*(radius*2+1) + (pixel[0]+radius)#???

**Comment by danielvarga** [comment]
pixel_code is a way to turn an (x,y) pixel position into a single integer. pixel_code=0 means top left pixel, pixel_code=1 is the one to the right, pixel_code=2*radius+1 means the one below, etc.

**Comment by arrrrrrrri** [comment]
What is the overall logic of these codes?Here is my personal understanding, I don't know if it's correct or not:
1、assume there is N hooks,so there will be N(N-1)/2 valid strings
2、the circular image composed of pixels can be turned to a vector **b**
3、strings can also be turned to vectors of the same length of vector **b**,{x_1,x_2...x_{N(N-1)/2} = A
4、solve the equation Ax ≈ b
I watched some videos like this one(https://www.youtube.com/watch?v=WGccIFf6MF8&t=23s).But I am still quite confused as the code is not the same as I thought.QAQ
